vscode:
  extensions:
    - ritwickdey.LiveServer@5.6.1:wV4LBkq6Z5s1xwf2HrB+cw==
    - abusaidm.html-snippets@0.2.1:7b7Vkkp6Lem9WOqKCYMq2w==
    - xabikos.JavaScriptSnippets@1.7.2:XXmiw8r7K3Guifex/E73aQ==